// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwxlzhdtvhggniyzfhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d3hsemhkdHZoZ2duaXl6Zmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTIwNjcsImV4cCI6MjA2Njk2ODA2N30.ynzMHFSO59rKlBR98gq0ZBdsOi9BhiVruP84R76V9e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});